version: '3.4'

services:
  dingoquadruped:
    image: dingo_ws
    network_mode: "host"
    privileged: true
    cap_add:
      - SYS_PTRACE
      - SYS_RAWIO    # 很多时候操作底层内存需要这个特权
    security_opt:
      - seccomp:unconfined   
    volumes:
      - ./dingo_ws:/dingo_ws
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /sys:/sys      # 必须给GPIO留的活口
    devices:
      - /dev:/dev
      - /dev/gpiomem:/dev/gpiomem   # 为 RPi.GPIO 硬开路
      - /dev/mem:/dev/mem           # SPI 时常需要用到的绝对内存
